In [9]:
import numpy as np

r = np.array([[1, 1],
              [1, 1],
              [1, 1],
              [1, 1]])

p = np.array([[0, 0],
              [2, 3],
              [4, 5],
              [7, 9]])

dx, dy = (r-p)[:, 0], (r-p)[:, 1]

sq = 

SyntaxError: invalid syntax (884524675.py, line 18)

In [1]:
string = "x = 5"
exec(string)

5


In [2]:
str([1, 2, 3])

'[1, 2, 3]'

In [11]:
import yaml
with open(rf'/home/aleksandr/Research/social_nav_baselines/planners/configs/dwa_config.yaml') as f:
        config = yaml.safe_load(f)
for k,v in config.items():
    string = k + " = " + str(v)
    exec(string)

print(X_rob_init)



<class 'list'>


In [ ]:
import numpy as np
a = np.array([[1, 1, 1, 1],
              [2, 2, 3, 2]])
b = np.zeros([10, *np.shape(a)])
dt = 0.1
b[0, :, :] = a
# copy velocities
b[1:, :, 2:] = b[0, :, 2:]
# propagate coordinates
for step in range(1, 10):
    b[step, :, :2] = b[step-1, :, :2] + b[step-1, :, 2:] * dt

b

In [4]:
a, b, c = [1, 2, 3]
a

1

In [2]:
import numpy as np
a = np.zeros([10, 3])
a[0, :] = [1, 2, 3]
v = 0.1
w = 0.3


array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import numpy as np
ground_truth_pedestrians_state = np.array([1000, 1000, 0, 0])
ground_truth_pedestrians_state[0]

1000

In [1]:
import numpy as np
np.array(list(map(int, input().split())))

array([1, 1, 1])

In [4]:
print(*list(np.array([1, 1, 1])))

1 1 1


In [33]:
print("The goal", *["{0:0.2f}".format(i) for i in [2, 3, 4.3624654]], "was reached!")

The goal 2.00 3.00 4.36 was reached!


In [37]:
import numpy as np
a = np.array([[1, 1, 1],
              [0, 0, 0]])

b = np.concatenate([a, [[2, 2, 2]]])
b


array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

In [46]:
total_peds = 2
a = np.zeros([total_peds, 2])
b = np.ones([total_peds, 2])
a = np.concatenate([a, b])
b

array([[1., 1.],
       [1., 1.]])

In [45]:
a = np.concatenate([a, b])
a

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
a = np.array([3., 0., 0.])
b = np.array([1., 1., 1.])
a = np.stack([a, b])
a = np.concatenate([a, [b]])
a

[[3. 0. 0.]
 [1. 1. 1.]]


array([[3., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
l = []
l.append([3., 0., 0.])
l.append([1., 1., 1.])
l.append([0, 0, 0])
np.asarray(l)

array([[3., 0., 0.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [66]:
def hex_to_rgb(value: str):
    """Function convert HEX format color to RGB

    Args:
        value (str): HEX color: '#f2a134'

    Returns:
        Tuple[int]: RGB color: (242, 161, 52)
    """
    value = value.lstrip('#')
    lv = len(value)
    return tuple(int(value[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

c = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
a = []
for color in c:
    a.append(hex_to_rgb(color))
print(a)

[(31, 119, 180), (255, 127, 14), (44, 160, 44), (214, 39, 40), (148, 103, 189), (140, 86, 75), (227, 119, 194), (127, 127, 127), (188, 189, 34), (23, 190, 207)]


In [9]:
a = set([1, 2, 3, 4])
a.remove(1)
a

{2, 3, 4}